INSERT INTO entrenador (nombre, apellidos, email, fecha_nacimiento, telefono, especialidad, ruta_imagen, descripcion)
VALUES
('Carlos', 'García', 'carlos.garcia@example.com', '1980-05-15', '612 345 678', 'Entrenador Personal', '/images/entrenadores/carlos.jpg', 'Experto en entrenamiento funcional, Carlos ha ayudado a muchas personas a alcanzar sus objetivos de fitness mediante programas personalizados y un enfoque motivador.'),
('María', 'López', 'maria.lopez@example.com', '1985-08-22', '622 345 678', 'Instructora de Yoga', '/images/entrenadores/maria.jpg', 'Especialista en yoga y meditación, María ofrece clases que combinan técnicas de relajación con ejercicios de estiramiento para mejorar la flexibilidad y la tranquilidad mental.'),
('José', 'Martínez', 'jose.martinez@example.com', '1978-12-30', '632 345 678', 'Entrenador de Fuerza', '/images/entrenadores/jose.jpg', 'Entrenador de fuerza y acondicionamiento, José se enfoca en el desarrollo de la fuerza muscular y la resistencia a través de programas intensivos y estructurados.'),
('Ana', 'Fernández', 'ana.fernandez@example.com', '1990-07-07', '642 345 678', 'Instructora de Pilates', '/images/entrenadores/ana.jpg', 'Instructora certificada de pilates, Ana ofrece clases que fortalecen el núcleo del cuerpo, mejoran la postura y aumentan la flexibilidad con un enfoque holístico.'),
('Luis', 'Gómez', 'luis.gomez@example.com', '1983-03-17', '652 345 678', 'Entrenador de Crossfit', '/images/entrenadores/luis.jpg', 'Coach de Crossfit y entrenamiento de alta intensidad, Luis es conocido por sus desafiantes sesiones que mejoran tanto la resistencia cardiovascular como la fuerza muscular.'),
('Elena', 'Díaz', 'elena.diaz@example.com', '1992-11-25', '662 345 678', 'Entrenadora de Running', '/images/entrenadores/elena.jpg', 'Especialista en entrenamiento de corredores, Elena ha desarrollado programas que optimizan el rendimiento en carreras de corta y larga distancia, y mejoran la técnica de carrera.'),
('Javier', 'Ruiz', 'javier.ruiz@example.com', '1987-01-05', '672 345 678', 'Entrenador de Natación', '/images/entrenadores/javier.jpg', 'Entrenador de natación con más de 10 años de experiencia, Javier ha trabajado con nadadores de todos los niveles para mejorar su técnica y resistencia en el agua.'),
('Laura', 'Hernández', 'laura.hernandez@example.com', '1995-09-10', '682 345 678', 'Entrenadora de Ciclismo', '/images/entrenadores/laura.jpg', 'Experta en ciclismo indoor y outdoor, Laura ofrece programas de entrenamiento que mejoran la resistencia cardiovascular y la fuerza en las piernas, adaptados a ciclistas de todos los niveles.'),
('Miguel', 'Torres', 'miguel.torres@example.com', '1982-06-02', '692 345 678', 'Entrenador de Boxeo', '/images/entrenadores/miguel.jpg', 'Entrenador de boxeo y artes marciales, Miguel combina técnicas tradicionales de boxeo con modernas estrategias de entrenamiento para mejorar la agilidad, la fuerza y la resistencia.'),
('Carmen', 'Sánchez', 'carmen.sanchez@example.com', '1988-02-14', '672 345 679', 'Instructora de Baile', '/images/entrenadores/carmen.jpg', 'Instructora de baile y zumba, Carmen ofrece clases energéticas y divertidas que combinan el ejercicio aeróbico con ritmos de baile para mejorar la salud cardiovascular y la coordinación.'),
('Ricardo', 'Ramírez', 'ricardo.ramirez@example.com', '1981-04-19', '682 345 679', 'Entrenador de Kickboxing', '/images/entrenadores/ricardo.jpg', 'Especialista en kickboxing y defensa personal, Ricardo enseña técnicas que mejoran la fuerza, la agilidad y la autoconfianza en sus estudiantes.'),
('Patricia', 'Romero', 'patricia.romero@example.com', '1993-07-28', '692 345 679', 'Entrenadora de Fitness', '/images/entrenadores/patricia.jpg', 'Entrenadora personal certificada en fitness, Patricia crea planes de entrenamiento personalizados que ayudan a sus clientes a alcanzar sus objetivos de salud y bienestar.'),
('Juan', 'Ortiz', 'juan.ortiz@example.com', '1977-10-21', '672 345 680', 'Instructor de Artes Marciales', '/images/entrenadores/juan.jpg', 'Instructor de artes marciales mixtas, Juan ha entrenado a numerosos estudiantes en diversas disciplinas, mejorando su técnica, fuerza y resistencia.'),
('Isabel', 'Castillo', 'isabel.castillo@example.com', '1991-12-05', '682 345 680', 'Entrenadora de Gimnasia', '/images/entrenadores/isabel.jpg', 'Entrenadora de gimnasia rítmica y artística, Isabel ha trabajado con gimnastas de todos los niveles, ayudándolos a perfeccionar sus habilidades y alcanzar su máximo potencial.'),
('Sergio', 'Vega', 'sergio.vega@example.com', '1984-08-13', '692 345 680', 'Entrenador de Atletismo', '/images/entrenadores/sergio.jpg', 'Entrenador de atletismo y preparación física, Sergio ofrece programas de entrenamiento que mejoran la velocidad, la resistencia y la técnica de sus atletas.'),
('Marta', 'Navarro', 'marta.navarro@example.com', '1986-11-15', '662 345 679', 'Entrenadora de Triatlón', '/images/entrenadores/marta.jpg', 'Entrenadora de triatlón, Marta prepara a sus atletas para competir en triatlones mediante programas que integran natación, ciclismo y carrera, mejorando su resistencia y rendimiento en las tres disciplinas.');
